In [10]:
c = 'Hello World' 
print(c[0])

H


In [15]:
L1 = [2,3,5,3,4,5,7,8]

L = []
for i in L1: 
    if i not in L: 
        L.append(i) 

print(L)

[2, 3, 5, 4, 7, 8]


In [17]:
sample = "abc@gmail.com" 
print(sample[:sample.find('@')])



abc


In [21]:
L1 = [2,3,5,3,4,5,7,8] 
print(list({i for i in L1}))

[2, 3, 4, 5, 7, 8]


In [23]:
Sunil = {"Name": "Sunil", "Gender": "Male"} 
Sunil 

{'Name': 'Sunil', 'Gender': 'Male'}

In [24]:
D1 = {'Name': 'Rohit', 'College': 'IMT', 'Marks': {'M1': 56, 'DS': 54, 'Eng': 67}}
D1

{'Name': 'Rohit', 'College': 'IMT', 'Marks': {'M1': 56, 'DS': 54, 'Eng': 67}}

In [26]:
D1['College']

'IMT'

In [27]:
D1['Marks']['DS']

54

In [28]:
#editting in the dictionary 
D1['Marks']['DS']=64

In [29]:
D1

{'Name': 'Rohit', 'College': 'IMT', 'Marks': {'M1': 56, 'DS': 64, 'Eng': 67}}

In [31]:
D1.get('Name')

'Rohit'

In [32]:
# adding a new eliment in dictionary 
D1['Age'] = 23

In [33]:
D1

{'Name': 'Rohit',
 'College': 'IMT',
 'Marks': {'M1': 56, 'DS': 64, 'Eng': 67},
 'Age': 23}

In [34]:
del D1['College']


In [35]:
D1

{'Name': 'Rohit', 'Marks': {'M1': 56, 'DS': 64, 'Eng': 67}, 'Age': 23}

In [36]:
for i in D1: 
    print(i)

Name
Marks
Age


In [37]:
for i in D1: 
    print(D1[i])

Rohit
{'M1': 56, 'DS': 64, 'Eng': 67}
23


In [38]:
for i in D1: 
    print(i,D1[i])

Name Rohit
Marks {'M1': 56, 'DS': 64, 'Eng': 67}
Age 23


In [3]:
def my_decorator(func): 
    def wrapper(): 
        print("Starting..") 
        func() 
        print("Finished!") 
    return wrapper

@my_decorator 
def greet(): 
    print("Good Morining!")
    
greet()


Starting..
Good Morining!
Finished!


In [8]:
a = '5'; print(int(a))

5


In [52]:
a = 'Hello World' 
#list_a = list(a) 
print(list(i for i in a))
   

    

['H', 'e', 'l', 'l', 'o', ' ', 'W', 'o', 'r', 'l', 'd']


In [14]:
str1 = 'I Love Data Science' 
print(str1.split())

['I', 'Love', 'Data', 'Science']


In [17]:
str1_l = list(str1)
print(str1_l)

['I', ' ', 'L', 'o', 'v', 'e', ' ', 'D', 'a', 't', 'a', ' ', 'S', 'c', 'i', 'e', 'n', 'c', 'e']


In [18]:
words = ['I', 'Love', 'Data', 'Science']
print(words[::-1])

['Science', 'Data', 'Love', 'I']


In [19]:
a

'Hello World'

In [20]:
print(a[::-1])

dlroW olleH


In [21]:
def reverse_string(s): 
    clean_s = s.lower().split()
    return clean_s[::-1]
list_1 = 'I Love Data Science' 
print(reverse_string(list_1))

['science', 'data', 'love', 'i']


In [23]:
list_1 = [2,3,5,3,2,4,5,6]
print(list({i for i in list_1}))

[2, 3, 4, 5, 6]


In [24]:
import pandas as pd 
import numpy as np 

In [25]:
arr1 = np.array([1,3,4,5,6]) 
arr2 = arr1[::-1] 
print(arr2)

[6 5 4 3 1]


In [27]:
arr3 = np.flip([1,3,5,6])
print(arr3)

[6 5 3 1]


In [32]:
arr_3 = np.array([2,3,5,4])
x = np .delete(arr_3,3) 
x



array([2, 3, 5])

In [34]:
arr_3[3] = 8
arr_3

array([2, 3, 5, 8])

In [42]:
list1 = ['w', 'a', 'w', 'b'] 
list_2 = ['e', 're', 'riting','log'] 
lst3 = [x + y for x,y in zip(list1, list_2)] 
print(lst3)

['we', 'are', 'writing', 'blog']


In [46]:
print([x**2 for x in range(0,10)])


[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]


In [47]:
list_1 = [0, 1, 4, 9, 16, 25, 36, 49, 64, 81] 
lst_final = [] 
for x in lst: 
    lst_final.append(x*x) 
print(lst_final)

[1, 4, 9, 16]
